### PR TITLE
Set min ndk version to API 21 for armeabi-v7a and x86

### PR DESCRIPTION
**Pull request by bitmold**
@eighthave I made this change regarding #140 - I believe these are set to 19 as a mistake. Orbot targets API 21 and for that matter tor browser for android sets this to 21 for each abi too

### CODE REVIEW

**Comment by bitmold** [comment]
Oh and yea, with NDK 26 these ABIs won't build if set to less than 21

**Review by syphyr — COMMENTED** [review]
~~Mips NDK_PLATFORM_LEVEL should also be changed to 21 and `minSdkVersion` should be bumped to 21 in both build.gradle files.~~

I misunderstood the purpose of this PR.  Please ignore.

**Comment by bitmold** [comment]
https://github.com/guardianproject/tor/pull/6 is also necessary for building with NDK 26

**Comment by bitmold** [comment]
@syphyr after merging this I was able to build tor-android into Orbot targeting `arm64-v8a` and did not get the segmentation fault you had mentioned. With this PR merged as well as the PR i had made to the patched guardianproject/tor repo merged, you can build with the latest NDK LTS release. 
@n8fr8 @uniqx @n8fr8

**Comment by syphyr** [comment]
> @syphyr after merging this I was able to build tor-android into Orbot targeting `arm64-v8a` and did not get the segmentation fault you had mentioned. With this PR merged as well as the PR i had made to the patched guardianproject/tor repo merged, you can build with the latest NDK LTS release. @n8fr8 @uniqx @n8fr8

Strange, its still crashing for me.

```
05-14 03:02:29.222  3175  3214 E AndroidRuntime: FATAL EXCEPTION: tor
05-14 03:02:29.222  3175  3214 E AndroidRuntime: Process: org.torproject.android, PID: 3175
05-14 03:02:29.222  3175  3214 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void org.torproject.jni.TorService.mainConfigurationFree() (tried Java_org_torproject_jni_TorService_mainConfigurationFree and Java_org_torproject_jni_TorService_mainConfigurationFree__)
05-14 03:02:29.222  3175  3214 E AndroidRuntime: 	at org.torproject.jni.TorService.mainConfigurationFree(Native Method)
05-14 03:02:29.222  3175  3214 E AndroidRuntime: 	at org.torproject.jni.TorService.-$$Nest$mmainConfigurationFree(TorService.java)
05-14 03:02:29.222  3175  3214 E AndroidRuntime: 	at org.torproject.jni.TorService$3.run(TorService.java:385)
```

**Pull request closed without merging**
