### PR TITLE
kotlin compose webview

### PR DESCRIPTION
**Pull request by holywend**
using previous sampletorapp to build kotlin compose webview with the latest dependencies

### CODE REVIEW

**Comment by n8fr8** [comment]
Great idea, thanks for the submission!

**Comment by syphyr** [comment]
Perhaps updating the dependencies in external/ should be separate commits.  I see that zlib should also be bumped to 1.2.13 tag.

**Comment by holywend** [comment]
@syphyr ah you are absolutely correct, I should probably not do that in this PR. ill fix and just PR the sample-tor-compose directory.

**Comment by holywend** [comment]
Any idea how to do that? I think that's caused by the Makefile? should we gitignore it?

**Pull request merged**
