### PR TITLE
update to tor 0.4.7.7

### PR DESCRIPTION
**Pull request by bitmold**

### CODE REVIEW

**Comment by bitmold** [comment]
The readme change is in here, unless I'm missing something else

**Comment by eighthave** [comment]
First test build: https://gitlab.com/eighthave/tor-android/-/pipelines/557618977

**Comment by eighthave** [comment]
Doh sorry, I see the README change now, sorry I was blind.

**Comment by 05nelsonm** [comment]
May also wanna test to see if it will still run on API 20 and below. May need to bump minSdk.

**Comment by bitmold** [comment]
@05nelsonm I'm curious specifically what in tor breaks older Android releases.

I noticed that same comment in your release note for this Tor series on kmp-tor https://github.com/05nelsonm/kmp-tor

**Comment by bitmold** [comment]
I'm sorry, didn't see your linked comment

**Pull request merged**
