### PR TITLE
Sample App Works

### PR DESCRIPTION
**Pull request by bitmold**
The sample app in this project has always been very barebones, but I noticed it wasn't kept up to date and wasn't working at all.

The first commit here gets the project to build on a fresh clone of this repository. The second gets the app running again, while updating libraries to latest tor-android, and generally updating the app's code to look like a more modern Android app.

image

This commit is the bare minimum to get it working again.

### CODE REVIEW

**Comment by eighthave** [comment]
Looks good to me, I say merge it!  Nice initiative too!  I really appreciate seeing things like this being maintained.

**Comment by bitmold** [comment]
For sure, I think it would be worthwhile to have a more developed sample app and move it out of this repository. That way it could have documentation about how to make something with the libraries here and people who are just interested in that can see a very simple codebase. 

I ended up wanting to run the sample because I've been trying to toy around with a version of tor-android that uses arti instead of c tor

**Comment by eighthave** [comment]
yeah, a well developed example would be good to have.  In one sense, the Tor 
Services app is a version of that.

I also think it still makes sense to keep this example here and keep it as 
simple as possible.  It is the "getting started" example.

**Comment by eighthave** [comment]
Turns out that this broke the build in CI:
* https://gitlab.com/eighthave/tor-android/-/jobs/1821468195
* https://gitlab.com/guardianproject/tor-android/-/jobs/1821499082

**Comment by bitmold** [comment]
I wrote a comment explaining what's going on here in #58

**Pull request merged**
